README.md, documentation/GOVERNANCE.md
Adds a description for the governance process for the model development and links this process from the Readme file.
=> adds description of sldt model governance process

io.catenax.single_level_bom_as_planned/1.0.0/metadata.json, io.catenax.single_level_usage_as_built/1.0.0/metadata.json
Both models contain syntax issues, which are fixed in 1.0.1. Thus they have to be deprecated to prevent further usage.
-->
Closes #
=> Deprecate single level bom as planned 1.0.0 and single level usage as planned 1.0.0 

README.md
=> fixes link to CONTRIBUTING.md in README.md

io.catenax.reuse_certificate/1.0.0/ReuseCertificate.ttl, io.catenax.reuse_certificate/1.0.0/metadata.json, io.catenax.reuse_certificate/RELEASE_NOTES.md
=> ReuseCertificate reopen PR due to ECA failure

io.catenax.refurbishing_certificate/1.0.0/RefurbishingCertificate.ttl, io.catenax.refurbishing_certificate/1.0.0/metadata.json, io.catenax.refurbishing_certificate/RELEASE_NOTES.md
=> RefurbishingCertificate reopen PR due to ECA failure

io.catenax.decomissioning_certificate/1.0.0/DecommissioningCertificate.ttl, io.catenax.decomissioning_certificate/1.0.0/metadata.json, io.catenax.decomissioning_certificate/RELEASE_NOTES.md
=> [New model]: initial model of decomissioning certificate

README.md, documentation/BAMM-method-documentation,-tool-and-training.md, documentation/GOVERNANCE.md, documentation/Getting-Started-with-Aspect-Modeling-based-on-BAMM.md
Signed-off-by: Johannes Kristan <Johannes.kristan@bosch.com>
Updates references in the README from BAMM to SAMM and adds a reference to the currently used CLI version.
=> Update references from BAMM to SAMM

io.catenax.just_in_sequence_part/1.0.0/JustInSequencePart.ttl, io.catenax.just_in_sequence_part/1.0.0/metadata.json, io.catenax.just_in_sequence_part/RELEASE_NOTES.md
based on work of PR #106 
Closes PR #106
=> Add just in sequence part 1.0.0 (based on work of PR#106)

io.catenax.part_as_planned/1.0.1/PartAsPlanned.ttl, io.catenax.part_as_planned/1.0.1/metadata.json, io.catenax.part_as_planned/RELEASE_NOTES.md
See PR #87 for details
Closes PR #87
=> Add part as planned 1.0.1 (based on work of PR#87)

.github/PULL_REQUEST_TEMPLATE.md
Add checklist item the ask for copyright holder
=> Add checklist item copyright holder

SECURITY.md
=> Add SECURITY.md to repository

io.catenax.week_based_capacity_group/1.0.0/WeekBasedCapacityGroup.ttl, io.catenax.week_based_material_demand/1.0.0/WeekBasedMaterialDemand.ttl
Update the copyright notice contained in the header of the `WeekBasedMaterialDemand` and `WeekBasedCapacityGroup` aspect models to reflect the contributions of the companies involved in the creation of those.
_Note: The other MS2 criteria had already been met._
_Note: The other MS3 criteria had already been met._
=> Update copyright notice in models` header

io.catenax.parts_analyses/1.0.0/metadata.json
Set old model version to deprecated
With feature request 162 the new model version PartsAnalyses:2.0.0 will be released.
The old/current version has missing properties that makes it impossible to merge the data with e.g. data from ProductDescription semantic model.
Request is to set currrent model to deprecated.
-->
Closes #
=> io.catenax.parts_analyses:1.0.0: Set to deprecation

README.md
Signed-off-by: Johannes Kristan <Johannes.kristan@bosch.com>
This adds the status STANDARDIZED to the repository and make the relevant changes to the documentation and scripting.
=> Introduced status STANDARDIZED 

.github/PULL_REQUEST_TEMPLATE.md
Clarifies two checks according to discussions
=> Add further details to MS2 and MS3

io.catenax.product_stock/README.md, io.catenax.product_stock/RELEASE_NOTES.md
As discussed in last modelling session, the README was wrong - it should be RELEASE_NOTES.
=> fix(ProductStock): changed README to RELEASE_NOTES and set version

io.catenax.single_level_usage_as_planned/1.0.0/metadata.json
New Model version given. 
-->
Closes #240
=> Model SingleLevelUsageAsPlanned 1.0.0 Deprecation metadata.json

io.catenax.single_level_bom_as_planned/1.0.1/metadata.json
New Model version given
-->
Closes #239
=> Model SingleLevelBomAsPlanned 1.0.1 Deprecation metadata.json

io.catenax.part_as_planned/1.0.1/metadata.json
New Model given
-->
Closes #234
=> Model PartAsPlanned 1.0.0 Deprecate metadata.json

io.catenax.assembly_part_relationship/1.1.1/metadata.json
New model Version. 
-->
Closes #231 
=> Model AssemblyPartRelationship 1.1.1 Deprecate: metadata.json 

generate.sh
Updates the version of the SAMM-CLI in the generate.sh script in order to support SAMM Models as well.
=> Update gen artifacts

io.catenax.battery.battery_pass/3.0.0/metadata.json
=> change status to standardize for battery_pass 3.0.0

io.catenax.essincident/1.0.0/metadata.json
Model EssIncident 1.0.0 deprecation as new model 2.0.0 exist
-->
Closes #282 
=> Model EssIncident deprecation 1.0.0

.github/PULL_REQUEST_TEMPLATE.md
Adds check if previous model can be deprecated
=> AD MS3 check for model deprecation of previous model

io.catenax.shared.business_partner_number/1.0.0/BusinessPartnerNumber.ttl, io.catenax.shared.business_partner_number/1.0.0/metadata.json, io.catenax.shared.business_partner_number/RELEASE_NOTES.md
As proposed in the review of PR #295 , I created the MS2 first. MS1 will be added afterwards, so that we can directly do the MS3 next week.
Instead of just proposing BPNS, I propose them all with characteristic definitions from the standard document.
Closes #302 
=> [New Model]: Shared Aspect for BPN

.github/ISSUE_TEMPLATE/model_update_request.md, .github/ISSUE_TEMPLATE/new_model_request.md
In the modeling session we aligned on having a checklist entry to assign a modelling steward in MS1.
I added a check to following templates
- new model
- update model
=> Issue Templates: Add checklist entry to assign modeling steward in MS1

release.sh
=> Add initial version of release script

generate.sh
Updated the samm-cli version to samm-cli-2.3.2
=> Update to samm-cli-2.3.2

.github/actions/model-validation/action.yml
=> Update SAMM version to 2.3.2

io.catenax.single_level_bom_as_planned/1.1.0/metadata.json
Model deprecate single_level_bom_as_planned
closes #372
=> [Model deprecate]:single_level_bom_as_planned:1.1.0

io.catenax.serial_part_typization/2.0.0/metadata.json
=> [Model deprecate]:serial_part_typization:2.0.0

io.catenax.serial_part_typization/1.1.1/metadata.json
Model deprecate serial_part_typization:1.1.1
closes #369
=> [Model deprecate]:serial_part_typization:1.1.1

io.catenax.request_for_quotation/1.0.0/RequestForQuotation.ttl, io.catenax.request_for_quotation/1.0.0/metadata.json, io.catenax.request_for_quotation/RELEASE_NOTES.md
*Resiliency Domain/Manufacturing as a Service*
Implements the new model "Request for Quotation"
Closes #307
```json
{
"rfqConfiguration": {
"firstDeliveryDate": "2023-10-24",
"additionalFiles": {},
"cadFile": {},
"additionalComments": "this is a prototype, recommendations towards design for manufacturing are highly welcome",
"parts": {
"generalTolerance": "ISO 2768-1 (m), Rough DIN ISO 2768 cL, Medium DIN ISO 2768 mK, Fine DIN ISO 2768 fH",
"additionalQualityRequirements": "premium quality check, standard quality check",
"manufacturingDomain": "additive manufacturing",
"postProcesses": {
"postProcessGroup": "heat treatment, surface treatment, surface finishing...",
"postProcessProperty": "black (for colouring)",
"postProcessType": "stress relieving, sandblasting, colouring"
}, …
```
=> Request for Quotation

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/governance.yml
Update samm cli version to 2.3.2
=> Feat: Updated samm cli version to 2.3.2

io.catenax.generic.digital_product_passport/1.0.0/metadata.json
[Model Deprecation]: urn:bamm:io.catenax.generic.digital_product_passport:1.0.0
closes #341
=> Model deprecation:digital_product_passport:1.0.0

io.catenax.shared.address_characteristic/4.0.0/AddressAspect.ttl, io.catenax.shared.address_characteristic/4.0.0/metadata.json, io.catenax.shared.address_characteristic/RELEASE_NOTES.md, io.catenax.shared.contact_information/4.0.0/ContactInformation.ttl, io.catenax.shared.contact_information/4.0.0/metadata.json, io.catenax.shared.contact_information/RELEASE_NOTES.md, io.catenax.shared.message_header/3.0.0/MessageHeaderAspect.ttl, io.catenax.shared.message_header/3.0.0/metadata.json, io.catenax.shared.message_header/RELEASE_NOTES.md, io.catenax.shared.physical_dimension/3.0.0/PhysicalDimensions.ttl, io.catenax.shared.physical_dimension/3.0.0/metadata.json, io.catenax.shared.physical_dimension/RELEASE_NOTES.md, io.catenax.shared.quantity/2.0.0/Quantity.ttl, io.catenax.shared.quantity/2.0.0/metadata.json, io.catenax.shared.quantity/RELEASE_NOTES.md, io.catenax.shared.uuid/2.0.0/Uuid.ttl, io.catenax.shared.uuid/2.0.0/metadata.json, io.catenax.shared.uuid/RELEASE_NOTES.md
shared aspect models upgraded to samm 2.1.0 from 2.0.0
=> Upgraded the samm-meta model to 2.1.0 for shared models

.github/PULL_REQUEST_TEMPLATE.md, .github/actions/model-validation/action.yml, .github/workflows/bulk-validation.yml, .github/workflows/governance.yml, README.md, generate.sh
upgrade samm cli version to 2.5.1 and aspect model editor 5.1.1
=> upgrade samm cli version to 2.5.1 and aspect model editor 5.1.1

io.catenax.week_based_material_demand/2.0.0/WeekBasedMaterialDemand.ttl, io.catenax.week_based_material_demand/2.0.0/metadata.json, io.catenax.week_based_material_demand/RELEASE_NOTES.md
=> Bamm to Samm conversion

io.catenax.individual_asset_definition/2.0.0/IndividualAssetDefinition.ttl, io.catenax.individual_asset_definition/2.0.0/metadata.json, io.catenax.individual_asset_definition/RELEASE_NOTES.md
Bamm to Samm conversion for IndividualAssetDefinition 1.0.0
=> Bamm to Samm conversion-IndividualAssetDefinition

.github/workflows/upload-single-model.yml
Added Github action to upload single model
=> Added Github action to upload single model

.github/workflows/upload-single-model.yml
GitHub action upload single model
=> GitHub action upload single model

.github/actions/validate-single/index.js, .github/workflows/upload-single-model.yml
=> modified action

io.catenax.days_of_supply/1.0.0/DaysOfSupply.ttl, io.catenax.days_of_supply/1.0.0/metadata.json, io.catenax.days_of_supply/RELEASE_NOTES.md
Days of Supply in logistics is a metric used to estimate how long current inventory levels will last under normal consumption patterns. Days of Supply metric is used in supply chain management and it assists in forecasting when new stock is needed, thereby preventing stock shortages or overstocking. It plays a significant role in ensuring efficient inventory turnover, maintaining a balance between having enough stock to meet demand and avoiding excess inventory that ties up capital.
-->
Closes #526 
=> [New Model]: DaysOfSupply 1.0.0

io.catenax.transmission.transmission_pass/1.0.0/metadata.json
Model-Deprecate-Transmission-pass-1.0.0
=> Model-Deprecate-Transmission-pass-1.0.0

io.catenax.sealant.sealant_pass/1.0.0/metadata.json
Model deprecated sealant-pass-1.0.0
=> Model-deprecate-sealant-pass-1.0.0

io.catenax.user_estimated_loading/2.0.0/UserEstimatedLoading.ttl, io.catenax.user_estimated_loading/2.0.0/metadata.json, io.catenax.user_estimated_loading/RELEASE_NOTES.md
Bamm-to-Samm-conversion-UserEstimatedLoading-1.0.0
=> Bamm-to-Samm-conversion-UserEstimatedLoading-1.0.0

io.catenax.classified_load_spectrum/2.0.0/ClassifiedLoadSpectrum.ttl, io.catenax.classified_load_spectrum/2.0.0/metadata.json, io.catenax.classified_load_spectrum/RELEASE_NOTES.md
Bamm-to-Samm conversion of classified_load_spectrum-1.0.0
=> Bamm-to-Samm-classified_load_spectrum-1.0.0

io.catenax.rul/2.0.0/RemainingUsefulLife.ttl, io.catenax.rul/2.0.0/metadata.json, io.catenax.rul/RELEASE_NOTES.md
Converting Bamm-to-Samm-rul-1.0.0
=> Bamm-to-Samm-rul-1.0.0

io.catenax.eol_story/2.0.0/EndOfLife.ttl, io.catenax.eol_story/2.0.0/metadata.json, io.catenax.eol_story/RELEASE_NOTES.md
=> Bamm-to-Samm-eol_story-1.0.0

io.catenax.material_for_homologation/2.0.0/MaterialForHomologation.ttl, io.catenax.material_for_homologation/2.0.0/metadata.json, io.catenax.material_for_homologation/RELEASE_NOTES.md
Bamm-to-Samm-material_for_homologation-1.0.0
=> Bamm-to-Samm-material_for_homologation-1.0.0

io.catenax.part_as_specified/3.0.0/PartAsSpecified.ttl, io.catenax.part_as_specified/3.0.0/metadata.json, io.catenax.part_as_specified/RELEASE_NOTES.md
Bamm-to-Samm-part_as_specified-2.0.0
=> Bamm-to-Samm-part_as_specified-2.0.0

io.catenax.product_stock/2.0.0/ProductStock.ttl, io.catenax.product_stock/2.0.0/metadata.json, io.catenax.product_stock/RELEASE_NOTES.md
Bamm-to-Samm-product_stock-1.0.0
=> Bamm-to-Samm-product_stock-1.0.0

io.catenax.battery.product_description/2.0.0/ProductDescription.ttl, io.catenax.battery.product_description/2.0.0/metadata.json, io.catenax.battery.product_description/RELEASE_NOTES.md
Bamm-to-Samm-battery-product_description-1.0.1
=> Bamm-to-Samm-battery-product_description-1.0.1

io.catenax.certificate_of_destruction/2.0.0/CertificateOfDestruction.ttl, io.catenax.certificate_of_destruction/2.0.0/metadata.json, io.catenax.certificate_of_destruction/RELEASE_NOTES.md
Bamm-to-Samm-certificate_of_destruction-1.0.1
=> Bamm-to-Samm-certificate_of_destruction-1.0.1

io.catenax.generic.digital_product_passport/5.0.0/DigitalProductPassport.ttl, io.catenax.generic.digital_product_passport/RELEASE_NOTES.md
fixes earlier version of DPP upload
-->
Closes #
=> [Model Update]: Digital Product Passport

io.catenax.material_flow_scenario_request/2.0.0/MaterialFlowScenarioRequestAspect.ttl, io.catenax.material_flow_scenario_request/2.0.0/metadata.json, io.catenax.material_flow_scenario_request/RELEASE_NOTES.md
-->
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/725
```json
{
"materialFlowScenarioRequest": {
"scenarioSimResults": {
"resultOwnId": "916b5688-8bd8-4d7e-83b9-e0d40939274e",
"resultOwnSimRunInitial": {
"owner": {
"bpns": "BPNS00000007OTZ3"
},
"dataQuality": 0,
"description": "Please simulate asap",
"comment": "successful simulation ",
"expirationTimestamp": "2023-03-24T09:15:24.000Z",
"runId": "0fece48b-c8d1-4180-1a9caca6d67e",
"shipments": [
{
"handlingUnits": [
{
"name": "Palette",
"volume": 1,
"weight": 189,
"batches": [
{
"unitOfMeasurement": "KG",
"materialName": "KK1000GR-Gehäuse-Rot",
"quantity": 50,
"materialNumber": "KK1000GR",
"materialHazardousGoods": false,
"batchSerialNumber": "Batch_1",
"batchOrderId": "Order-0001",
"batchExpirationTimestamp": …
```
=> Material Flow Scenario Request v2.0.0

io.catenax.quality_task/1.0.0/metadata.json, io.catenax.quality_task/RELEASE_NOTES.md
=> Deprecation of quality_task:1.0.0

io.catenax.parts_analyses/2.0.0/metadata.json, io.catenax.parts_analyses/RELEASE_NOTES.md
=> Deprecation of parts.analyses 2.0.0

io.catenax.fleet.diagnostic_data/1.0.0/metadata.json, io.catenax.fleet.diagnostic_data/RELEASE_NOTES.md
=> Deprecate fleet.diagnostic:1.0.0

io.catenax.fleet.claim_data/1.0.0/metadata.json, io.catenax.fleet.claim_data/RELEASE_NOTES.md
=> Deprecate fleet.claim:1.0.0

io.catenax.secondary_material_content/1.0.0/metadata.json, io.catenax.secondary_material_content/RELEASE_NOTES.md, io.catenax.secondary_material_content_calculated/RELEASE_NOTES.md, io.catenax.secondary_material_content_verifiable/RELEASE_NOTES.md, io.catenax.shared.secondary_material_content/RELEASE_NOTES.md
This PR sets the release Status of these models to 'Released'
- [secondary_material_content_calculated](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.secondary_material_content_calculated)
- [secondary_material_content_verifiable](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.secondary_material_content_verifiable)
- [secondary_material_content](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.shared.secondary_material_content)
All three of these Models have been 'MS3-approved' and merged based on this [PR-506](https://github.com/eclipse-tractusx/sldt-semantic-models/pull/506) 
With the Release of the three models above the previous model is deprecated. Its deprecation is mentioned in this …
=> Update release notes SMC

LICENSE
License file name reverted to old name
=> Fix: License file name revert

.github/workflows/trufflehog.yml
As mandatory in this issue #780 / https://github.com/eclipse-tractusx/sig-security/issues/86 I have added the workflow to this repo.
Closes #780
=> feat: added the trufflehog workflow

.github/workflows/generate-artifacts.yml
=> ci: prevent artifact generation in forks

io.catenax.demand_and_capacity_notification/3.0.0/DemandAndCapacityNotification.ttl, io.catenax.demand_and_capacity_notification/3.0.0/metadata.json, io.catenax.demand_and_capacity_notification/RELEASE_NOTES.md
=> [Model Update] Enhance DemandAndCapacityNotification
