eclipse-tractusx/sldt-semantic-models

- .github/ISSUE_TEMPLATE/model_deprecation_request.md
- .github/ISSUE_TEMPLATE/model_update_request.md
- .github/ISSUE_TEMPLATE/new_model_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
This PR adds issue and PR templates to be used as part of the initial governance process. It closes #5
> adds issue and PR templates

- io.catenax.battery.battery_pass/3.0.0/BatteryPass.ttl
- io.catenax.battery.battery_pass/3.0.0/metadata.json
- io.catenax.battery.battery_pass/RELEASE_NOTES.md
Move BatteryPass3.0.0 in Tractus-X Repository
Closes #
> Create BatteryPass3.0.0 in Tractus-X Repository

- io.catenax.fleet.claim_data/1.0.0/ClaimData.ttl
- io.catenax.fleet.claim_data/1.0.0/metadata.json
- io.catenax.fleet.claim_data/RELEASE_NOTES.md
- io.catenax.fleet.diagnostic_data/1.0.0/DiagnosticData.ttl
- io.catenax.fleet.diagnostic_data/1.0.0/metadata.json
- io.catenax.fleet.diagnostic_data/RELEASE_NOTES.md
- io.catenax.manufactured_parts_quality_information/1.0.0/ManufacturedPartsQualityInformation.ttl
- io.catenax.manufactured_parts_quality_information/1.0.0/metadata.json
- io.catenax.manufactured_parts_quality_information/RELEASE_NOTES.md
- io.catenax.parts_analyses/1.0.0/PartsAnalyses.ttl
- io.catenax.parts_analyses/1.0.0/metadata.json
- io.catenax.parts_analyses/RELEASE_NOTES.md
- io.catenax.quality_task/1.0.0/QualityTask.ttl
- io.catenax.quality_task/1.0.0/metadata.json
- io.catenax.quality_task/RELEASE_NOTES.md
- io.catenax.vehicle.product_description/2.0.0/ProductDescription.ttl
- io.catenax.vehicle.product_description/2.0.0/metadata.json
- io.catenax.vehicle.product_description/RELEASE_NOTES.md
I transferred the QAX models from internal CX githup to open TractusX githup - Initial commit for CX release 3
6 aspect models from live quality use case(QAX) for CX release 3.
5 aspect models are new, Vehicle.ProductDescription is now available in Version 2.0.0
MS2 and MS3 criteria copied over from internal githup repository
> CX release 3: Transfer QAX aspect  models from internal githup to TractusX

- .github/actions/upload/Readme.md
- .github/actions/upload/action.yml
- .github/actions/upload/index.js
- .github/actions/validate/Readme.md
- .github/actions/validate/action.yml
- .github/actions/validate/index.js
- .github/workflows/governance.yml
- .github/workflows/upload.yml
adds actions for detecting changes in PRs and uploading them to a semantic hub
> initial process automation and upload to semantic hub

- .github/workflows/governance.yml
This PR changes the ref for the governance workflow from the head of the feature branch back to the merge commit.
> Use merge instead of head commit for governance workflow

- .github/workflows/upload.yml
These changes use the new octocat API with `github.rest.actions` instead of `github.actions`.
> Fix problem with using old octocat api

- .github/actions/model-validation/action.yml
- .github/actions/model-validation/index.js
- .github/actions/model-validation/package-lock.json
- .github/actions/model-validation/package.json
- .github/workflows/bulk-validation.yml
- .github/workflows/governance.yml
- .github/workflows/upload.yml
These changes add a new workflow that validates new and updated models and adds a comment for each new or updated model of a pull request.
Also, it is possible to run a validation job manually that runs over all existing models on a branch and delivers a detailed validation report for all models.
> Add model validation workflow

- io.catenax.essincident/1.0.0/EssIncident.ttl
- io.catenax.essincident/1.0.0/metadata.json
- io.catenax.essincident/RELEASE_NOTES.md
Move new model essIncident to Tractus-X
MS1, MS2, MS3 approved on former repository
-->
Closes #
> add EssIncident model

- io.catenax.part_as_specified/1.0.1/PartAsSpecified.ttl
- io.catenax.part_as_specified/1.0.1/metadata.json
- io.catenax.part_as_specified/RELEASE_NOTES.md
> PartAsSpecified reopen PR due to ECA failure

- documentation/GOVERNANCE.md
Signed-off-by: Johannes Kristan <Johannes.kristan@bosch.com>
Add a description on who to use comments instead of labels
> Add description on using comments instead of labels in GOVERNANCE.md

- io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl
- io.catenax.battery.battery_pass/3.0.1/metadata.json
- io.catenax.battery.battery_pass/RELEASE_NOTES.md
> [Model Update]: BatteryPass: several smaller fixes according to technical commitee feedback

- io.catenax.rul/1.0.0/RemainingUsefulLife.ttl
- io.catenax.rul/1.0.0/metadata.json
- io.catenax.rul/RELEASE_NOTES.md
added already released rul model
Closes #
> add remaining useful life model

- io.catenax.single_level_bom_as_planned/1.1.0/SingleLevelBomAsPlanned.ttl
- io.catenax.single_level_bom_as_planned/1.1.0/metadata.json
- io.catenax.single_level_bom_as_planned/RELEASE_NOTES.md
Based on work of PR #101
Closes #101
> Add single level bom as planned 1.1.0 (based on work of PR#101)

- io.catenax.asset_tracker_links/1.0.0/AssetTrackerLinks.ttl
- io.catenax.asset_tracker_links/1.0.0/metadata.json
- io.catenax.asset_tracker_links/RELEASE_NOTES.md
New model AssetTrackerLinks required by the product Asset Tracking (BD Sustainability)
-->
Closes #56 
> New submodel AssetTrackerLinks

- io.catenax.pcf/3.0.0/Pcf.ttl
- io.catenax.pcf/3.0.0/metadata.json
- io.catenax.pcf/RELEASE_NOTES.md
> PCF new BAMM version 2.0.0

- io.catenax.serial_part_typization/2.0.0/SerialPartTypization.ttl
- io.catenax.serial_part_typization/2.0.0/metadata.json
- io.catenax.serial_part_typization/RELEASE_NOTES.md
> [Model Update]:SerialPartTypization 2.0.0 with BAMM 2.0.0

- io.catenax.part_as_specified/1.0.2/PartAsSpecified.ttl
- io.catenax.part_as_specified/2.0.0/PartAsSpecified.ttl
- io.catenax.part_as_specified/2.0.0/metadata.json
- io.catenax.part_as_specified/RELEASE_NOTES.md
> [Model Update] Part As Specified

- io.catenax.week_based_capacity_group/1.0.0/WeekBasedCapacityGroup.ttl
- io.catenax.week_based_material_demand/1.0.0/WeekBasedMaterialDemand.ttl
Update the copyright attribution contained in the header of the `WeekBasedMaterialDemand` and `WeekBasedCapacityGroup` aspect models.
> Fix erroneous copyright attribution

- io.catenax.week_based_material_demand/1.0.1/WeekBasedMaterialDemand.ttl
- io.catenax.week_based_material_demand/1.0.1/metadata.json
- io.catenax.week_based_material_demand/RELEASE_NOTES.md
Changed description for property changedAt in model
io.catenax.week_based_material_demand
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/156
> Update description for property changedAt in week based material demand

- io.catenax.pcf/4.0.0/Pcf.ttl
- io.catenax.pcf/4.0.0/metadata.json
- io.catenax.pcf/RELEASE_NOTES.md
Implementation of necessary adaptations in order to ensure compatibility of the PCF data model with the current specifications of WBCSD (World Business Council for Sustainable Development) and the PCF Rulebook.
-->
Closes #165 
> [Model-Update] PCF: Update for compatibility with specification WBCSD v2 and PCF Rulebook v2

- io.catenax.traction_battery_code/1.0.0/TractionBatteryCode.ttl
- io.catenax.traction_battery_code/1.0.0/metadata.json
- io.catenax.traction_battery_code/RELEASE_NOTES.md
The traction battery code is a requirement that the Chinese government has for every traction battery that will be exported to China. It is an identification code using a set of numerals and English letters that contain certain information meaning and indicate main attributes and uniqueness of traction battery according to GB/T 34014-2017.
The same model can be used for all three battery component types (pack, module, cell).
Closes #134 
> Traction battery code

- io.catenax.manufacturing_capability/1.0.0/ManufacturingCapability.ttl
- io.catenax.manufacturing_capability/1.0.0/metadata.json
- io.catenax.manufacturing_capability/RELEASE_NOTES.md
This PR introduces the first version (1.0.0) of the manufacturing capability aspect model.
Refers to #158 
> Adding first version of the manufacturing capability aspect model.

- .github/ISSUE_TEMPLATE/model_standardize_request.md
- documentation/GOVERNANCE.md
Adds a new issue template to transfer a model into status standardize
@arnoweiss wdyt?
> Add template for standardization issue

- io.catenax.vehicle.product_description/3.0.0/ProductDescription.ttl
- io.catenax.vehicle.product_description/3.0.0/metadata.json
- io.catenax.vehicle.product_description/RELEASE_NOTES.md
- model updated to SAMM:2.0.0. This is needed that the model can be used as external reference in 
PR https://github.com/eclipse-tractusx/sldt-semantic-models/pull/175
- entities relinked - see readme.md for details
> Updated data model io.catenax.vehicle.product_description to SAMM:2.0.0

- io.catenax.fleet.vehicles/1.0.0/Vehicles.ttl
- io.catenax.fleet.vehicles/1.0.0/metadata.json
- io.catenax.fleet.vehicles/RELEASE_NOTES.md
This PR creates a new semantic model, that allows to transfer multiple vehicle descriptions.
The new model references Vehicle.ProductDescription in version 3.0.0
> [New Model]: Feature 163, List of Vehicle Product Discription needed for QAX and Catena-X release 3.2

- io.catenax.shared.address_characteristic/3.0.0/AddressAspect.ttl
change adress to address
change example for post code from "68161\\12" to "98765-4321" and change adress to address
-->
Closes #
> change example for post code from "68161\\12" to "98765-4321"

- io.catenax.single_level_bom_as_planned/2.0.0/SingleLevelBomAsPlanned.ttl
- io.catenax.single_level_bom_as_planned/2.0.0/metadata.json
- io.catenax.single_level_bom_as_planned/RELEASE_NOTES.md
Since the colleague [jacewski-bosch](https://github.com/jacewski-bosch) is on parental leave, we aren't able to update the exsting PR #204.
Therefore we created a new PR based 1:1 on the existing PR #204 with the original content of the branch _single_level_bom_as_planned_2.0.0_ from the fork _jacewski-bosch/sldt-semantic-models_ to be able to continue the MS approval check.
Closes #204 and #203.
> Follow up SingleLevelBomAsPlanned_2.0.0

- io.catenax.batch/2.0.0/Batch.ttl
- io.catenax.batch/2.0.0/metadata.json
- io.catenax.batch/RELEASE_NOTES.md
Updated to Batch 2.0.0. Added Regular expression for KeyCharacteristic and removed properties nameAtCustomer and customerId for compliance reasons. 
-->
Closes #281
> Batch 2.0.0

- io.catenax.shared.uuid/1.0.0/Uuid.ttl
- io.catenax.shared.uuid/1.0.0/metadata.json
- io.catenax.shared.uuid/RELEASE_NOTES.md
As proposed in the review of PR #295, I created the MS2 first. MS1 will be added afterwards, so that we can directly do the MS3 next week.
-->
Closes #301 
> [New Model]: Shared Aspect for UUID v4

- .github/PULL_REQUEST_TEMPLATE.md
The template had to small faulty information
- mentioned BAMM instead of SAMM
- validation command was outdated
Following criteria was updated:
(MS2 Criteria)
> Fix: PR template mentioned BAMM and SAMM

- io.catenax.id_based_request_for_update/1.0.0/IdBasedRequestForUpdate.ttl
- io.catenax.id_based_request_for_update/1.0.0/metadata.json
- io.catenax.id_based_request_for_update/RELEASE_NOTES.md
requested model for DcmUuidBasedRfu
Closes #
#137 
> New model: IdBasedRequestForUpdate 

- io.catenax.battery.battery_pass/2.0.0/metadata.json
io.catenax.battery.battery_pass:2.0.0
closes #333
> [Model deprecation]: io.catenax.battery.battery_pass:2.0.0

- io.catenax.esr_certificates.esr_certificate/1.0.1/metadata.json
deprecate io.catenax.esr_certificates.esr_certificate:1.0.1
close #338
> [Model deprecation]:io.catenax.esr_certificates.esr_certificate:1.0.1

- io.catenax.single_level_bom_as_built/2.0.0/SingleLevelBomAsBuilt
- io.catenax.single_level_bom_as_built/2.0.0/SingleLevelBomAsBuilt.ttl
- io.catenax.single_level_bom_as_built/2.0.0/metadata.json
- io.catenax.single_level_bom_as_built/RELEASE_NOTES.md
Major change in in the SingleLevelBomAsBuilt Model. Change was needed due to the required representation of items that are not included in the AsBuilt lifecycle (e.g. Serial parts or batches). Thus, provides the possibility to add parts on a type level. 
-->
Closes #248 
> [Model Update]: SingleLevelBomAsBuilt 

- io.catenax.material_flow_simulation_result/2.0.0/MaterialFlowSimulationResultAspect.ttl
- io.catenax.material_flow_simulation_result/2.0.0/metadata.json
- io.catenax.material_flow_simulation_result/RELEASE_NOTES.md
Add an additional layer for the SimulationResult for reusability. The current model lacks a reusable entity for MaterialFlowSimulationResult, which can be reused in other models.
Closes #315
> Material Flow Simulation Result v2.0.0

- io.catenax.manufacturing_capability/2.0.0/ManufacturingCapability.ttl
- io.catenax.manufacturing_capability/2.0.0/metadata.json
- io.catenax.manufacturing_capability/RELEASE_NOTES.md
The model has been converted using the Aspect Model Editor and validated using samm-cli-2.3.2
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/393
> ManufacturingCapability v.2.0.0: Migration to SAMM

- io.catenax.material_flow_scenario_request/1.0.0/MaterialFlowScenarioRequestAspect.ttl
- io.catenax.material_flow_scenario_request/1.0.0/metadata.json
- io.catenax.material_flow_scenario_request/RELEASE_NOTES.md
Implementation of the material flow scenario request.
The model requires the latest version of Material Flow Simulation Result v2.0.0 https://github.com/eclipse-tractusx/sldt-semantic-models/pull/329
Closes #316
> Material Flow Scenario Request v1.0.0

- io.catenax.week_based_capacity_group/1.0.0/metadata.json
deprecating week_based_capacity_group:1.0.0
closes #384
> [Model deprecation]: week_based_capacity_group:1.0.0

- io.catenax.single_level_usage_as_built/1.0.1/metadata.json
[Model Deprecate]:single_level_usage_as_built:1.0.1 
closed #374
> [Model Deprecate]:single_level_usage_as_built:1.0.1

- README.md
> Update samm-cli in README.md

- io.catenax.id_based_comment/1.0.0/IdBasedComment.ttl
Correction of TextRegularExpression description io.catenax.id_based_comment:1.0.0 from 1.000 to 5.000 to follow property description and regex definition.
Closes #
> Correction of TextRegularExpression description io.catenax.id_based_comment:1.0.0

- io.catenax.iot_sensor_device_definition/2.0.0/IotSensorDeviceDefinition.ttl
- io.catenax.iot_sensor_device_definition/2.0.0/metadata.json
- io.catenax.iot_sensor_device_definition/RELEASE_NOTES.md
-->
* Converted from BAMM to SAMM.
Closes #428
> Update IotSensorDeviceDefinition v.2.0.0

- io.catenax.asset_tracker_links/2.0.0/AssetTrackerLinks.ttl
- io.catenax.asset_tracker_links/2.0.0/metadata.json
- io.catenax.asset_tracker_links/RELEASE_NOTES.md
-->
AssetTrackerLinks model is based upon the standardized Data Chain template. As that template has been updated, we need to make changes as well in our aspect model.
- rename childCatenaXId to catenaXId
- rename childParts to childItems
- convert from BAMM to SAMM
Closes #429
> Update AssetTrackerLinks v.2.0.0

- .gitignore
- io.catenax.generic.digital_product_passport/3.0.0/DigitalProductPassport.ttl
- io.catenax.generic.digital_product_passport/3.0.0/metadata.json
- io.catenax.generic.digital_product_passport/RELEASE_NOTES.md
> [Model Update]: Digital Product Passport

- io.catenax.refurbishing_certificate/2.0.0/RefurbishingCertificate.ttl
- io.catenax.refurbishing_certificate/2.0.0/metadata.json
- io.catenax.refurbishing_certificate/RELEASE_NOTES.md
As mentioned in issue https://github.com/eclipse-tractusx/sldt-semantic-models/issues/326 and in pull request https://github.com/eclipse-tractusx/sldt-semantic-models/pull/420. A new version of this model is generated.
-->
Closes #326 
> [Model Update]: RefurbishingCertificate_v2.0.0

- io.catenax.material_recycling_certificate/1.0.0/MaterialRecyclingCertificate.ttl
- io.catenax.material_recycling_certificate/1.0.0/metadata.json
- io.catenax.material_recycling_certificate/RELEASE_NOTES.md
As mentioned in issue https://github.com/eclipse-tractusx/sldt-semantic-models/issues/328 and in pull request https://github.com/eclipse-tractusx/sldt-semantic-models/pull/420. A new version of this model is generated.
-->
Closes #328 
> [New Model]: MaterialRecyclingCertificate_v1.0.0

- io.catenax.reuse_certificate/2.0.0/ReuseCertificate.ttl
- io.catenax.reuse_certificate/2.0.0/metadata.json
- io.catenax.reuse_certificate/RELEASE_NOTES.md
As mentioned in issue https://github.com/eclipse-tractusx/sldt-semantic-models/issues/324 and in pull request https://github.com/eclipse-tractusx/sldt-semantic-models/pull/420. A new version of this model is generated.
-->
Closes #324 
> [Model Update]: ReuseCertificate_v2.0.0

- io.catenax.remanufacturing_certificate/2.0.0/RemanufacturingCertificate.ttl
- io.catenax.remanufacturing_certificate/2.0.0/metadata.json
- io.catenax.remanufacturing_certificate/RELEASE_NOTES.md
As mentioned in issue https://github.com/eclipse-tractusx/sldt-semantic-models/issues/325 and in pull request https://github.com/eclipse-tractusx/sldt-semantic-models/pull/420. A new version of this model is generated.
-->
Closes #325 
> [Model Update]: RemanufacturingCertificate_v2.0.0

- io.catenax.waste_certificate/1.0.0/WasteCertificate.ttl
- io.catenax.waste_certificate/1.0.0/metadata.json
- io.catenax.waste_certificate/RELEASE_NOTES.md
As mentioned in issue https://github.com/eclipse-tractusx/sldt-semantic-models/issues/327 and in pull request https://github.com/eclipse-tractusx/sldt-semantic-models/pull/420. A new version of this model is generated.
-->
Closes #327 
> [New Model]: WasteCertificate_v1.0.0

- io.catenax.request_for_quotation/2.0.0/RequestForQuotation.ttl
- io.catenax.request_for_quotation/2.0.0/metadata.json
- io.catenax.request_for_quotation/RELEASE_NOTES.md
*Resiliency Domain / Manufacturing as a Service*
- Standardization of Request for Quotation exclusively for individual parts.
- Result: No longer a need for a detailed parts list.
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/486
```json
{
"rfqConfiguration": {
"firstDeliveryDate": "2023-10-24",
"additionalFiles": {
"fileName": "fraesteil",
"fileObject": {},
"fileType": "STEP, stl, jt",
"filePath": "digitaltwinregistry"
},
"cadFile": {
"fileName": "fraesteil",
"fileObject": {},
"fileType": "STEP, stl, jt",
"filePath": "digitaltwinregistry"
},
"additionalComments": "this is a prototype, recommendations towards design for manufacturing are highly welcome",
"parts": {
"generalTolerance": "ISO 2768-1 (m), Rough DIN ISO 2768 cL, Medium DIN ISO 2768 mK, Fine DIN ISO …
```
> [Model Update]: Request for Quotation v2.0.0

- io.catenax.batch/2.0.1/Batch.ttl
- io.catenax.batch/2.0.1/metadata.json
- io.catenax.batch/RELEASE_NOTES.md
Based on the results / definition of the Industry Core, the Batch aspect model needs to be extended by the part site information. The changes contain the integration of the new shared PartSiteInformationAsBuilt (#442) model as optional content.
Closes #487
> [Model Update]: Batch 2.0.1

- io.catenax.serial_part/2.0.0/SerialPart.ttl
- io.catenax.serial_part/2.0.0/metadata.json
- io.catenax.serial_part/RELEASE_NOTES.md
Based on the results / definition of the Industry Core, the SerialPart aspect model needs to be extended by the part site information. The changes contain the integration of the new shared PartSiteInformationAsBuilt (#442) model as optional content.
Additionally the model was migrated from BAMM to SAMM. -> major change for #R24.05.
Closes #485
> [Model Update]: SerialPart 2.0.0

- io.catenax.part_site_information_as_planned/1.0.0/metadata.json
Since a new shared PartSiteInformationAsBuilt model is needed, this version (incl. CX-0094 PartSiteInformationAsPlanned standard) will be set to 'deprecate'. This PR requires the approve and merge of #453 before it can be continued.
Closes #443
> [Model Deprecation]: PartSiteInformationAsPlanned 1.0.0 

- io.catenax.serial_part/1.0.1/metadata.json
Since an adaptation of the existing SerialPart model is needed, this version (incl. CX - 0019 Aspect Model SerialPart standard) will be set to 'deprecate'. An issue for the adapted SerialPart model is already created (https://github.com/eclipse-tractusx/sldt-semantic-models/issues/485) and is **mandatory before** the model can be **set to deprecate**.
Closes #490
> [Model Deprecation]: SerialPart 1.0.1

- io.catenax.batch/2.0.0/metadata.json
Since an adaptation of the existing Batch model is needed, this version (CX - 0021 Aspect Model: Batch standard) will be set to 'deprecate'. An issue for the adapted Batch model is already created (#487) and is **mandatory before** the model can be **set to deprecate**.
Closes #491
> [Model Deprecation]: Batch 2.0.0

- io.catenax.just_in_sequence_part/1.0.0/metadata.json
Since an adaptation of the existing JustInSequencePart model is needed, this version (currently not standardized) will be set to 'deprecate'. An issue for the adapted JustInSequencePart model is already created (#488) and is **mandatory before** the model can be **set to deprecate**.
Closes #492
> [Model Deprecation]: JustInSequencePart 1.0.0

- io.catenax.shared.message_header/1.0.0/metadata.json
Since we identified bugs of missing connection between a few properties and those respective traits, we have fixed this bug within this PR. Therefore the current version of this aspect model must be set deprecate.
**Note:** Can't be continued until the PR #476 was merged and closed!
Closes #507
> [Model Deprecation]: Shared MessageHeader 1.0.0

- io.catenax.single_level_bom_as_built/1.0.0/metadata.json
Since the SingleLevelBomAsBuilt aspect model is part of the Industry Core, the latest version 2.0.0 will be optional for the standard R24.03 and mandatory for standard R24.05. Therefore the previous version 1.0.0 should be set to 'deprecate'.
Closes #509
> [Model Deprecation]: SingleLevelBomAsBuilt 1.0.0

- io.catenax.shared.part_classification/1.0.0/PartClassification.ttl
- io.catenax.shared.part_classification/1.0.0/metadata.json
- io.catenax.shared.part_classification/RELEASE_NOTES.md
A new model was created. More information see:  Closes #520 
> [NEW MODEL]: PartClassification 1.0.0

- io.catenax.iot_sensor_data/1.0.0/metadata.json
[Model Deprecation]: IotSensorData v.1.0.0
Closes #495
> [Model Deprecation]: IotSensorData v.1.0.0

- io.catenax.iot_sensor_device_definition/1.0.0/metadata.json
[Model Deprecation]: IotSensorDeviceDefinition v.1.0.0
Closes #494
> [Model Deprecation]: IotSensorDeviceDefinition v.1.0.0

- io.catenax.shared.shopfloor_information_types/1.0.0/ShopfloorInformationTypes.ttl
- io.catenax.shared.shopfloor_information_types/1.0.0/metadata.json
- io.catenax.shared.shopfloor_information_types/2.0.0/ShopfloorInformationTypes.ttl
- io.catenax.shared.shopfloor_information_types/2.0.0/metadata.json
- io.catenax.shared.shopfloor_information_types/RELEASE_NOTES.md
Update of the Message_header to the latest version 
-->
Closes #535 
> [Model Update] shopfloor_information_types

- io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
- io.catenax.shopfloor_information.get_production_forecast/1.0.0/metadata.json
- io.catenax.shopfloor_information.get_production_forecast/2.0.0/GetProductionForecast.ttl
- io.catenax.shopfloor_information.get_production_forecast/2.0.0/metadata.json
- io.catenax.shopfloor_information.get_production_forecast/RELEASE_NOTES.md
Message Header and shopfloor_information_types are updated to version 2.0.0updated
-->
Closes #533 
> [Model Update] Get production forecast 2.0.0

- io.catenax.shared.business_partner_number/2.0.0/BusinessPartnerNumber.ttl
- io.catenax.shared.business_partner_number/2.0.0/metadata.json
- io.catenax.shared.business_partner_number/RELEASE_NOTES.md
-->
Closes #570 
Did not include SAMM update
Major version update needed? Overall it's less restricitve why it could also be a minor version change
> fix(BusinessPartnerNumber): adjusted regex to match CX-0010

- io.catenax.shared.quantity/2.0.0/Quantity.ttl
- io.catenax.shared.quantity/RELEASE_NOTES.md
-->
Closes #541 
Note: Did not yet update SAMM version
> fix(Quantity): changed quantity example value

- io.catenax.market_place_offer/2.0.0/MarketplaceOffer.ttl
- io.catenax.market_place_offer/2.0.0/metadata.json
- io.catenax.market_place_offer/RELEASE_NOTES.md
As mentioned in issue: https://github.com/eclipse-tractusx/sldt-semantic-models/issues/482.
-->
Closes #482 
> [Model Update]: market palce offer_v2.0.0

- io.catenax.return_request/2.0.0/ReturnRequest.ttl
- io.catenax.return_request/2.0.0/metadata.json
- io.catenax.return_request/RELEASE_NOTES.md
As mentioned in issue: https://github.com/eclipse-tractusx/sldt-semantic-models/issues/313.
-->
Closes #313 
> [Model Update]: return request_v2.0.0

- io.catenax.time_series_reference/1.0.0/metadata.json
> [Model Deprecation]: urn:bamm:io.catenax.time_series_reference:1.0.0

- io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
- io.catenax.part_type_information/1.0.0/metadata.json
- io.catenax.part_type_information/RELEASE_NOTES.md
..................................................................................................................................................................
This PR replaces the original request to adapt the PartAsPlanned -> #567 
..................................................................................................................................................................
Based on the continous development of the Industry Core, the existing **PartAsPlanned** aspect model will be renamed to **PartTypeInformation**. Therefore a new aspect model is needed, which contains the same functions as the previous PartAsPlanned 2.0.0.
Additionally these new topics will be done within the implementation of the new/renamed aspect model:
- Integration of the new shared …
> [New Model]: PartTypeInformation 1.0.0

- io.catenax.decomissioning_certificate/2.0.0/DecommissioningCertificate.ttl
- io.catenax.decomissioning_certificate/2.0.0/metadata.json
- io.catenax.decomissioning_certificate/RELEASE_NOTES.md
Bamm-to-Samm conversion decomissioning_certificate-1.0.0
> Bamm-to-Samm-decomissioning_certificate-1.0.0

- io.catenax.idconversion/2.0.0/IdConversion.ttl
- io.catenax.idconversion/2.0.0/metadata.json
- io.catenax.idconversion/RELEASE_NOTES.md
Bamm-to-Samm-idconversion-1.0.0
> Bamm-to-Samm-idconversion-1.0.0

- io.catenax.essincident/3.0.0/EssIncident.ttl
- io.catenax.essincident/3.0.0/metadata.json
- io.catenax.essincident/RELEASE_NOTES.md
update changes to essIncident data model acc. to industry core
- updated version of model
- update reference to shared aspect address
- update BPN-L/S/A and refer to shared model
- update IDs and refer to shared Uuidv4Characteristic
- delete product number
- adjust copyright info
Closes #572 
> [Model Update]: essIncident #572

- io.catenax.battery.product_description/1.0.1/metadata.json
[Model Deprecation]: urn:bamm:io.catenax.battery.product_description:1.0.1
closes #334
> [Model Deprecation]: urn:bamm:io.catenax.battery.product_description:1.0.1

- io.catenax.delivery_information/2.0.0/DeliveryInformation.ttl
- io.catenax.delivery_information/2.0.0/metadata.json
- io.catenax.delivery_information/RELEASE_NOTES.md
> [Model Update]: Harmonize DeliveryInformation to industry core

- io.catenax.quality_task/1.0.0/QualityTask.ttl
- io.catenax.quality_task/1.0.0/gen/QualityTask.json
bugfix: the date in the example does not match the schema.json of the submodel
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/pull/524
> Bug fix example value

- io.catenax.pcf/6.0.0/Pcf.ttl
- io.catenax.pcf/6.0.0/metadata.json
- io.catenax.pcf/RELEASE_NOTES.md
> [Model Update]Pcf

- io.catenax.short_term_material_demand/1.0.0/ShortTermMaterialDemand.ttl
- io.catenax.short_term_material_demand/1.0.0/metadata.json
- io.catenax.short_term_material_demand/RELEASE_NOTES.md
> feat(ShortTermMaterialDemand): added initial model

- io.catenax.failure_pattern/1.0.0/FailurePattern.ttl
- io.catenax.failure_pattern/1.0.0/metadata.json
- io.catenax.failure_pattern/RELEASE_NOTES.md
-->
Closes #[620](https://github.com/eclipse-tractusx/sldt-semantic-models/issues/620)
> [New Model]: Failure Pattern

- io.catenax.week_based_material_demand/3.0.0/WeekBasedMaterialDemand.ttl
- io.catenax.week_based_material_demand/3.0.0/metadata.json
- io.catenax.week_based_material_demand/RELEASE_NOTES.md
This is now the same data model as `MaterialDemand` in #587 without the property `demandRate`
Changes on the data model see RELEASE_NOTES.txt contained in this PR.
Closes #674
> [Model Update]: WeekBasedMaterialDemand 24.05 changes

- io.catenax.days_of_supply/1.0.0/metadata.json
New model version 2.0.0 was introduced in the issue #676
-->
Closes #697
> [Model Deprecation]: DaysOfSupply 1.0.0

- io.catenax.request_for_quotation/3.0.0/RequestForQuotation.ttl
- io.catenax.request_for_quotation/3.0.0/metadata.json
- io.catenax.request_for_quotation/RELEASE_NOTES.md
*Resiliency Domain / Manufacturing as a Service*
Replaced the previous description of process steps (Property 'processes') with Shared.bill_of_process (referencing MP's model) (Property 'billOfProcess')
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/660
> [Model Update]: Request for Quotation 3.0.0

- io.catenax.demand_and_capacity_notification/2.0.0/DemandAndCapacityNotification.ttl
- io.catenax.demand_and_capacity_notification/2.0.0/metadata.json
- io.catenax.demand_and_capacity_notification/RELEASE_NOTES.md
> feat(DemandAndCapacityNotification): added notificationIds

- io.catenax.material_flow_simulation_result/3.0.0/MaterialFlowSimulationResultAspect.ttl
- io.catenax.material_flow_simulation_result/3.0.0/metadata.json
- io.catenax.material_flow_simulation_result/RELEASE_NOTES.md
-->
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/726
```json
{
"materialFlowScenarioRequest": {
"scenarioSimResults": {
"resultOwnId": "916b5688-8bd8-4d7e-83b9-e0d40939274e",
"resultOwnSimRunInitial": {
"owner": {
"bpns": "BPNS00000007OTZ3"
},
"dataQuality": 0,
"description": "Please simulate asap",
"comment": "successful simulation ",
"expirationTimestamp": "2023-03-24T09:15:24.000Z",
"runId": "0fece48b-c8d1-4180-1a9caca6d67e",
"shipments": [
{
"handlingUnits": [
{
"name": "Palette",
"volume": 1,
"weight": 189,
"batches": [
{
"unitOfMeasurement": "KG",
"materialName": "KK1000GR-Gehäuse-Rot",
"quantity": 50,
"materialNumber": "KK1000GR",
"materialHazardousGoods": false,
"batchSerialNumber": "Batch_1",
"batchOrderId": "Order-0001",
"batchExpirationTimestamp": …
```
> Material Flow Simulation Result v3.0.0

- io.catenax.essincident/2.0.0/metadata.json
essIncident model version 2.0.0 shall be changed from release to deprecate
Use case ESS incident wants to deprecate older models as they are not in use yet and we want to make sure only the latest models will be available for implementation purpose
just one change: [Update metadata.json, set version essIncident v 2.0.0 to deprecate]
-->
Closes Issue [Model Deprecation]: ESS Incident version 2.0.0 #735
> [Model Deprecation]: ESS Update metadata.json version 2.0.0 to deprecate

- io.catenax.pcf/7.0.0/Pcf.ttl
- io.catenax.pcf/7.0.0/metadata.json
- io.catenax.pcf/RELEASE_NOTES.md
Update of the PCF data model in context of CX Rel. 24.08
-->
Closes #717 
> [MODEL_UPDATE] PCF for CX Rel. 24.08

- io.catenax.fleet.vehicles/1.0.0/metadata.json
- io.catenax.fleet.vehicles/2.1.0/metadata.json
- io.catenax.fleet.vehicles/RELEASE_NOTES.md
Catena-X use case quality decided to set old versions of this model to deprecated.
Closes #750 
> Deprecate old fleet.vehicles versions

- io.catenax.manufactured_parts_quality_information/1.0.0/metadata.json
- io.catenax.manufactured_parts_quality_information/RELEASE_NOTES.md
> Deprecate Manufactured QInfo:1.0.0

- io.catenax.shared.business_partner_certificate/1.0.0/BusinessPartnerCertificate.ttl
- io.catenax.shared.business_partner_certificate/2.0.0/BusinessPartnerCertificate.ttl
- io.catenax.shared.business_partner_certificate/2.0.0/metadata.json
- io.catenax.shared.business_partner_certificate/RELEASE_NOTES.md
This pull request updates `enclosedSiteBpn` property to accept both site and address type business partner. Additionally, the Validator object is made optional, including `validatorName` and `validatorBpn`, for increased flexibility in validation details.
Closes https://github.com/eclipse-tractusx/sldt-semantic-models/issues/771
> [Model Update]: business partner certificate update

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/model-validation/action.yml
- .github/workflows/bulk-validation.yml
- .github/workflows/governance.yml
- .gitignore
- README.md
- generate.sh
This PR updates:
- SAMM Speficiation from v2.0.0 to v2.1.0
- SAMM SDK from v2.6.0 to v2.9.5
- AME from v5.1.1 to v5.6.0
- .gitignore (added SAMM-CLI)
Closes: #769
> Fix: Updated SAMM-CLI to 2.9.5 and AME version to 5.6.0

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/model-validation/action.yml
- .github/workflows/bulk-validation.yml
- .github/workflows/governance.yml
- README.md
- generate.sh
This PR updates the SAMM CLI from v2.9.5 to v2.9.7.
Remark: Version 2.9.5 contains issues which prevents the validation of shared models in some cases. This is fixed with 2.9.7.
> Update SAMM-CLI from 2.9.5 to 2.9.7

- .github/workflows/re-generate-all-artefacts
This PR adds a new workflow to the SLDT-Semantic-Model repository.
Context: The SAMM CLI is updated regularly. Some of the updates fix issues with the generated artefacts as it was the case between SAMM CLI version 2.6 and 2.9.7 (see: https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.9.7). Since most of the models were generated with version 2.6, these artefacts are not generated according to the specification. All of these artefacts sometimes needs to be updated with the newest SAMM CLI version.
This PR adds a workflow which does exactly that. It re-generates all artefacts for each model, with the newest version (defined in the generate.sh).
Note: This script needs to be triggered manually, as it is only required, when the SAMM CLI is updated within this repository.
> Create re-generate-all-artefacts Workflow

- .github/workflows/re-generate-all-artefacts.yml
One last fix is required. 
The re-generation of all model artifacts worked completely fine. Unfortunately, I was not aware, that the artifacts won't be committed, if the "gen" folder does not exist in advance - in this case, the artifacts are created successfully, but for some reason not committed.
This PR fixes this.
> Fix (re-generate-all-artefacts.yml): Cover edge cases, where the gen-folder does not exist

- io.catenax.warranty_claim_request/1.0.0/WarrantyClaimRequest.ttl
- io.catenax.warranty_claim_request/1.0.0/metadata.json
- io.catenax.warranty_claim_request/RELEASE_NOTES.md
New model for exchange of warranty request data
-->
Closes [#808](https://github.com/eclipse-tractusx/sldt-semantic-models/issues/808)
> [New Model] Warranty Data Model - Warranty Claim Request

- io.catenax.report_8d/1.0.0/Report8D.ttl
- io.catenax.report_8d/1.0.0/metadata.json
- io.catenax.report_8d/RELEASE_NOTES.md
This model enables the implement of the 8D process via the Catena-X network.
This model supports the VDA-QDX standard of the 8D as well as the Global 8D standard
-->
Closes [855](https://github.com/eclipse-tractusx/sldt-semantic-models/issues/855)
> [New Model] io.catenax.report_8d:1.0.0 for Saturn release 2509

- io.catenax.quality_task_attachment/3.0.0/QualityTaskAttachment.ttl
- io.catenax.quality_task_attachment/3.0.0/metadata.json
- io.catenax.quality_task_attachment/RELEASE_NOTES.md
Adding a new version of the QualityTaskAttachment model.
Newest version uses the QualityCore model, added a new identifier for the attachment and changed the way of referencing to other semantic models.
-->
Closes [#805](https://github.com/eclipse-tractusx/sldt-semantic-models/issues/805)
> [Model Update] QualityTaskAttachment to 3.0.0 for Saturn release 2509

- io.catenax.generic.digital_product_passport/6.0.0/gen/DigitalProductPassport-context.jsonld
- io.catenax.pcf/7.0.0/gen/Pcf-context.jsonld
-->
Connected to this #866 PR, needed for the data trust & security kit, it was found with this tested now, that there is needed one attribute with the model name in the root @context
> hotfix: added unique aspect attribute

- io.catenax.pcf/7.0.0/gen/Pcf-context.jsonld
-->
I have found a problem but just in the PCF models. It includes in some properties the `allOf` property, which needs to be interpreted  differently by the translator tool.
#867 
#866 
Closes #
> metadata: added pcf `@context` with bugfix to `allOf`

- io.catenax.business_partner_certificate/3.1.0/gen/BusinessPartnerCertificate-context.jsonld
-->
Another use case that uses the Data Trust & security kit is the CCM
So we need the JSON-LD context
> metadata: added context ld for BusinessPartnerCertificate-context.jsonld

- io.catenax.business_partner_certificate/3.1.0/gen/BusinessPartnerCertificate-context.jsonld
- io.catenax.generic.digital_product_passport/6.0.0/gen/DigitalProductPassport-context.jsonld
- io.catenax.pcf/7.0.0/gen/Pcf-context.jsonld
-->
I found out that some attributes like `id` and `type` cant be overwritten and were not being included in the models. Now the models can include the `cx` prefix to include the id and type attributes in "root" level.
Closes #
> metadata: added extra context metadata which was missing
